[build]
    command = "CI= npm run build"
    publish = "out"
    environment = {  NEXT_IMAGE_ALLOWED_DOMAINS = "amazonaws.com,podboxx.com", FORCE_WEBP_OUTPUT="true" }
[[plugins]]
    package = "@netlify/plugin-nextjs"
